### ISSUE TITLE
Emissing textures does not emit light with LambDynamicLights

### ISSUE THREAD

**Issue by DelofJ** [Moonlight-MC/Figura#228]
When you have LambDynamicLights installed with Figura, even if there is an option to enable dynamic light sources with entities, the emissing texture from a Figura pack does not emit any dynamic light
Holding a light :
![2022-05-11_17 27 12](https://user-images.githubusercontent.com/50058956/167896435-e6cdd44b-6742-49e0-9999-aa0839c5b41f.png)
Only the skin with emissing texture :
![2022-05-11_17 27 15](https://user-images.githubusercontent.com/50058956/167896561-6cd1b143-437c-4e9a-bfee-c9c8b00d9ea4.png)

**Comment by DelofJ** [comment]
Yes, emissive textures are textures that glow in the dark, like in vanilla Minecraft
But with a mod intended to add Dynamic Lights like LambDynamicLights or OptiFine (which isn't compatible but it's for exemple)
Here it doesn't work with the player skin while it works with all other entities
Because the problem comes from the emissive textures of Figura I posted this problem here
I did not turn to the developer of LambDynamicLights because it seems to me that the mod is supposed to work with all emissive textures and Figura is the only one who doesn't work
But I could be wrong

**Comment by TheNukeLore** [comment]
Emmisives are not supposed to cause a whole mob to glow, imagine if you had 1 pixel on your skin to glow, then your whole skin would glow. Also look at spiders, their eyes are emmisive but ldl does not cause their whole body to glow. All emmisives actually do in Minecraft are render said pixel at full bright. Also the way figura works, it just uses the default Minecraft system for emmisives so if anything it’s not figura fault.

**Comment by DelofJ** [comment]
I used this skin just as an example, and thought that since the emmisives are like the vanilla emmisives, it should work with dynamic light mods but maybe not and it's not here to deal with it
If so, sorry for disturbing you

**Comment by DelofJ** [comment]
Yeah I think making an issue for this wasn't worth it, I think it's better to close it
