### ISSUE TITLE
Optifine Compatability

### ISSUE THREAD

**Issue by asjMoria** [Moonlight-MC/Figura#231]
Wondering if it's possible to make Figura compatible with Optifine as they currently conflict.

**Comment by TheNukeLore** [comment]
no, optifine is closed source which means we cant easily find and fix whatever issues it may be causing.

**Comment by Stonewall0210** [comment]
I’m not a developer but this has been discussed, and optifine causes too many issues to be compatible.

optifine’s codebase is years old anyway and there are many alternatives that give more performance than optifine ever did

**Comment by asjMoria** [comment]
Ok, thank you!
