### ISSUE TITLE
Figura requires any version of fabric, which is missing! (except it's not)

### ISSUE THREAD

**Issue by Auhrii** [Moonlight-MC/Figura#240]
I installed Fabric 0.14.8 and Figura Alpha 8, both for Minecraft 1.19, but when I try to start the game Figura claims it "requires any version of fabric, which is missing!" in the resulting Fabric Loader error window.

![image](https://user-images.githubusercontent.com/25776947/174873049-29d799c6-437f-4fd1-942f-579fd1dd7fa0.png)

Here's the error I get from copying:

> Incompatible mod set!
> net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
> A potential solution has been determined:
> 	 - Install fabric, any version.
> Unmet dependency listing:
> 	 - Mod 'Figura' (figura) 0.0.8+1.19 requires any version of fabric, which is missing!
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
>

**Comment by Lunariaa** [comment]
do you have fabric api installed?

**Comment by GrandpaScout** [comment]
"Fabric" is the [Fabric API](https://modrinth.com/mod/fabric-api)

**Comment by Auhrii** [comment]
I was under the impression the Fabric Loader was the same thing? The installer seems analogous to the Forge installer in that it creates a new profile and drops the appropriate API in. Is this not the case?

**Comment by Manuel-3** [comment]
No, Fabric API is a seperate mod, idk why that isnt just included in Fabric in the first place.
